# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
    
    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Get commit details
      id: commit_details
      run: |
        echo "cd_time=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "cd_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "cd_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Build
      run: |
        CGO_ENABLED=1 CC=musl-gcc go build -v -ldflags "-linkmode external -extldflags '-static' -X 'main.version=${{ env.cd_commit }} at ${{ env.cd_time }}'" -o server_exporter ./...

    - name: Test
      run: go test -v ./...

    - name: Calculate checksum
      run: |
        sha256sum server_exporter | awk '{print $1}' > server_exporter.sha256

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.cd_commit }}
        release_name: Release ${{ env.cd_commit }}
        body: |
          Build at ${{ env.cd_time }}
          Binary checksum: $(cat server_exporter.sha256)
          Commit message:
            ${{ env.cd_message }}
        draft: false
        prerelease: false

    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: server_exporter
    #     path: |
    #       server_exporter
    #       server_exporter.json
