# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
    
    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Get commit details
      id: vars
      run: |
        echo "cd_time=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "cd_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "cd_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Build server_exporter
      run: |
        CGO_ENABLED=1 CC=musl-gcc go build -v -ldflags "-linkmode external -extldflags '-static' -X 'main.version=${{ env.cd_commit }} at ${{ env.cd_time }}'" -o server_exporter server_exporter.go

    - name: Test server_exporter
      run: go test -v server_exporter.go

    - name: Calculate checksum
      run: |
        sha256sum server_exporter | awk '{print $1}' > server_exporter.sha256

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "$cd_commit"
        release_name: Release "$cd_commit"
        body: |
          Build at "$cd_time"
          Commit message:
            "$cd_message"
        draft: false
        prerelease: false

    - name: Get the upload URL for the release
      id: upload_url
      run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Upload release binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "$UPLOAD_URL"
        asset_path: ./server_exporter
        asset_name: server_exporter
        asset_content_type: application/octet-stream

    - name: Upload release sha256 checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "$UPLOAD_URL"
        asset_path: ./server_exporter.sha256
        asset_name: server_exporter.sha256
        asset_content_type: text/plain

    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: server_exporter
    #     path: |
    #       server_exporter
    #       server_exporter.json
