# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build server_exporter on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
    
    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Get commit ID
      id: vars
      run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Get build time
      id: buildtime
      run: echo "time=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        export CGO_ENABLED=1
        export CC=musl-gcc
        go build -v \
          -ldflags "-X main.version='${{ steps.vars.outputs.commit }} at ${{ steps.buildtime.outputs.time }}' -linkmode external -extldflags '-static'" \
          -o server_exporter ./...

    - name: Test
      run: go test -v ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: server_exporter
        path: server_exporter
        retention-days: 30
